In [3]:
import pandas as pd
import numpy as np

In [4]:
# import geolocation data
olist_geolocation_data = pd.read_csv('olist_geolocation_dataset.csv',\
                                    dtype={'geolocation_zip_code_prefix':str})
print(len(olist_geolocation_data))

1000163

In [5]:
olist_geolocation_data.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.545621,-46.639292,sao paulo,SP
1,01046,-23.546081,-46.644820,sao paulo,SP
2,01046,-23.546129,-46.642951,sao paulo,SP
3,01041,-23.544392,-46.639499,sao paulo,SP
4,01035,-23.541578,-46.641607,sao paulo,SP

In [6]:
olist_geolocation_data['geolocation_zip_code_prefix_1_digits'] = olist_geolocation_data['geolocation_zip_code_prefix'].str[0:1]
olist_geolocation_data['geolocation_zip_code_prefix_2_digits'] = olist_geolocation_data['geolocation_zip_code_prefix'].str[0:2]
olist_geolocation_data['geolocation_zip_code_prefix_3_digits'] = olist_geolocation_data['geolocation_zip_code_prefix'].str[0:3]
olist_geolocation_data['geolocation_zip_code_prefix_4_digits'] = olist_geolocation_data['geolocation_zip_code_prefix'].str[0:4]

In [7]:
olist_geolocation_data.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,geolocation_zip_code_prefix_1_digits,geolocation_zip_code_prefix_2_digits,geolocation_zip_code_prefix_3_digits,geolocation_zip_code_prefix_4_digits
0,01037,-23.545621,-46.639292,sao paulo,SP,0,01,010,0103
1,01046,-23.546081,-46.644820,sao paulo,SP,0,01,010,0104
2,01046,-23.546129,-46.642951,sao paulo,SP,0,01,010,0104
3,01041,-23.544392,-46.639499,sao paulo,SP,0,01,010,0104
4,01035,-23.541578,-46.641607,sao paulo,SP,0,01,010,0103

In [8]:
olist_geolocation_data['geolocation_zip_code_prefix'].value_counts().\
to_frame().describe()

       geolocation_zip_code_prefix
count                 19015.000000
mean                     52.598633
std                      72.057907
min                       1.000000
25%                      10.000000
50%                      29.000000
75%                      66.500000
max                    1146.000000

In [9]:
# Removing some outliers
#Brazils most Northern spot is at 5 deg 16′ 27.8″ N latitude.;
olist_geolocation_data = olist_geolocation_data[olist_geolocation_data.geolocation_lat <= 5.27438888]
#it’s most Western spot is at 73 deg, 58′ 58.19″W Long.
olist_geolocation_data = olist_geolocation_data[olist_geolocation_data.geolocation_lng >= -73.98283055]
#It’s most southern spot is at 33 deg, 45′ 04.21″ S Latitude.
olist_geolocation_data = olist_geolocation_data[olist_geolocation_data.geolocation_lat >= -33.75116944]
#It’s most Eastern spot is 34 deg, 47′ 35.33″ W Long.
olist_geolocation_data = olist_geolocation_data[olist_geolocation_data.geolocation_lng <=  -34.79314722]

In [10]:
# treat the latitute and longitude coordinates and transform then to Mercator x/y Coordinates.
from datashader.utils import lnglat_to_meters as webm

In [14]:
X,y = webm(olist_geolocation_data.geolocation_lat,olist_geolocation_data.geolocation_lng)
print(X,y)

0         -2.621087e+06
1         -2.621138e+06
2         -2.621143e+06
3         -2.620950e+06
4         -2.620636e+06
               ...
1000158   -3.124587e+06
1000159   -3.103267e+06
1000160   -3.124945e+06
1000161   -3.160241e+06
1000162   -3.124750e+06
Name: geolocation_lat, Length: 1000121, dtype: float64 0         -5.883395e+06
1         -5.884291e+06
2         -5.883988e+06
3         -5.883428e+06
4         -5.883770e+06
               ...
1000158   -6.802061e+06
1000159   -6.840890e+06
1000160   -6.802787e+06
1000161   -6.772485e+06
1000162   -6.803500e+06
Name: geolocation_lng, Length: 1000121, dtype: float64

In [16]:
olist_geolocation_data['X'] = pd.Series(X)
olist_geolocation_data['y'] = pd.Series(y)

In [17]:
olist_geolocation_data.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,geolocation_zip_code_prefix_1_digits,geolocation_zip_code_prefix_2_digits,geolocation_zip_code_prefix_3_digits,geolocation_zip_code_prefix_4_digits,X,y
0,01037,-23.545621,-46.639292,sao paulo,SP,0,01,010,0103,-2.621087e+06,-5.883395e+06
1,01046,-23.546081,-46.644820,sao paulo,SP,0,01,010,0104,-2.621138e+06,-5.884291e+06
2,01046,-23.546129,-46.642951,sao paulo,SP,0,01,010,0104,-2.621143e+06,-5.883988e+06
3,01041,-23.544392,-46.639499,sao paulo,SP,0,01,010,0104,-2.620950e+06,-5.883428e+06
4,01035,-23.541578,-46.641607,sao paulo,SP,0,01,010,0103,-2.620636e+06,-5.883770e+06

In [19]:
olist_geolocation_data['geolocation_zip_code_prefix'] = olist_geolocation_data['geolocation_zip_code_prefix'].astype(int)
olist_geolocation_data['geolocation_zip_code_prefix_1_digits'] = olist_geolocation_data['geolocation_zip_code_prefix_1_digits'].astype(int)
olist_geolocation_data['geolocation_zip_code_prefix_2_digits'] = olist_geolocation_data['geolocation_zip_code_prefix_2_digits'].astype(int)
olist_geolocation_data['geolocation_zip_code_prefix_3_digits'] = olist_geolocation_data['geolocation_zip_code_prefix_3_digits'].astype(int)
olist_geolocation_data['geolocation_zip_code_prefix_4_digits'] = olist_geolocation_data['geolocation_zip_code_prefix_4_digits'].astype(int)

In [22]:
brazil = olist_geolocation_data
agg_nme = 'geolocation_zip_code_prefix'
brazil[agg_nme].describe().to_frame()

       geolocation_zip_code_prefix
count                 1.000121e+06
mean                  3.657332e+04
std                   3.054939e+04
min                   1.001000e+03
25%                   1.107500e+04
50%                   2.653000e+04
75%                   6.350400e+04
max                   9.999000e+04

In [23]:
import holoviews as hv

ModuleNotFoundError: No module named 'holoviews'

In [21]:
plot_map(brazil,'Zip Codes in Brazil',ds.min(agg_nme),agg_name,cmap=rainbow)

NameError: name 'plot_map' is not defined